### ISSUE TITLE
Cannot Save New Criteria

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/badgeup-browser-client#10]
Attempting to save a new criterion throws errors in the browser's JS console and the page does not advance.

![image](https://user-images.githubusercontent.com/3623122/32975105-9529023e-cbc9-11e7-83bf-46334b277638.png)
[Chrome-log.badgeup.io-1510966800720.log](https://github.com/BadgeUp/badgeup-browser-client/files/1484225/dashboard.badgeup.io-1510966800720.log)

**Comment by MarkHerhold** [comment]
@Mohron Sorry about this and thanks for the feedback! It looks like we missed some validation on the dashboard.

Judging by your description, I think you should be setting:
* period = 1 day - these are the "chunks" of time we look at, e.g. log in each _day_
* Multiplicity = 5 (as you have it)
* lookback = 7 (as you have it)
* Consecutive = not checked (as you have it)

Those settings should work for you.

**Comment by MarkHerhold** [comment]
We updated the dashboard validation to catch your case and to be more clear. Please let me know if you run into any other issues. 👍

**Comment by Mohron** [comment]
Seems fine now. I made the criteria on my phone web browser with no issues
