### ISSUE TITLE
Allow Editing of API Keys

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/badgeup-browser-client#2]
Currently if you need to change the scope or description of an API key you are forced to remove the key, create a new one and update the application/client using the key.

**Comment by MarkHerhold** [comment]
Landed in `badgeup-node-client` and `badgeup-browser-client` in 0.4.1.

- You now can use the [dashboard](https://dashboard.badgeup.io/) to edit API keys
- [API Key](https://docs.badgeup.io/api/endpoint/UpdateApiKey/) docs are also updated

**Comment by Mohron** [comment]
I see this on the dashboard now. Perfect!
