### ISSUE TITLE
[Dashboard] Add a way to list Active Subjects

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/badgeup-browser-client#4]
Currently the Metrics tab when opened just has a search box and the message `No metrics found for subject "".`  It would be nice to have a way to list the subjects. I first tried searching names which didn't work of course but out of luck I was able to get data to display without anything in the search. Up until I saw this data I didn't think to search by UUID even though it's obvious now.

Also, make the table headers click-sort please!

**Comment by MarkHerhold** [comment]
@Mohron 
Great suggestion. 🎯 
This is actually already a planned feature (there are actually a lot of enhancements planned for the metrics tab).

**Comment by Mohron** [comment]
I can not load my subjects tab in the web dashboard currently. Overall the dashboard seems incredibly slow for me.

**Comment by MarkHerhold** [comment]
Yeah, we know about this. 😞 Accounts with heavy usage (that would include yours) are experiencing degraded performance. We have already begun working on a solution to scale up appropriately and should have it rolled out in the next few days.

Sorry about this.

**Comment by Mohron** [comment]
Ya I've been unable to do anything with it for a while because of this. I just never got around to reporting it...

**Comment by MarkHerhold** [comment]
Unfortunately this is not one of those 'quick fix' situations, but the good news is that it's pretty close to being ready. BadgeUp is consuming and evaluating incoming events correctly, it's just that any calculations against the events take way too long.

**Comment by MarkHerhold** [comment]
@Mohron The performance issues have been fixed. Give it a go. 👍

**Comment by Mohron** [comment]
@MarkHerhold I just happened to load up the dashboard today and noticed this. Thanks! Now hopefully  achievement/criteria progress by subject is next on the list.

**Comment by MarkHerhold** [comment]
And now we are beginning make some progress here!

The subjects tab now lets you drill into a single subject's details and view the subject's events histogram, overall progress towards an achievement, when it was last earned (if ever), and the subject's metrics.

There are plans for a fine-grained drill down into a subject's progress _per criterion_ as well among other simple analytics.

## Subject Details
![subject_details](https://cloud.githubusercontent.com/assets/4934732/24438726/65e8999a-1417-11e7-844a-3b3795d69f55.gif)

**Comment by Mohron** [comment]
Starting to look really good!

**Comment by Mohron** [comment]
I believe this requirement has been met so I'll go ahead and close this ticket.
