### ISSUE TITLE
[Dashboard] Add a way to reset data collected

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/badgeup-browser-client#5]
There should be a way to reset the data without creating a new application every time (plus I want to keep my criteria/achievements). This is big especially for testing. If you could, I'd like to see this feature soon!

**Comment by MarkHerhold** [comment]
@Mohron I agree, it would be very helpful to reset a user when testing. Do you want to be able to clear data for multiple/all subjects, or would clearing a single subject suffice?

For my notes, this is what we would be clearing:
- a subject's events
- a subject's metrics
- a subject's earned achievements

**Comment by Mohron** [comment]
@MarkHerhold Ultimately I think you should provide both options but any way to clear now would help me continue testing 👍. Whatever is closer on your radar is good enough for me.

**Comment by RobertHerhold** [comment]
@MarkHerhold We also need to remove dynamic criteria job results for the subject(s) as well

**Comment by Mohron** [comment]
Really looking forward to this even if it's not added to the web client first.

**Comment by MarkHerhold** [comment]
@Mohron I plan on shipping a really bad-looking version either **tonight** or **tomorrow**, withe the UI improving after that. I hope that will work for you.

**Comment by Mohron** [comment]
Ha ha I doubt it will be that bad. I'll be fine either way, I'm just trying to stay engaged.

**Comment by MarkHerhold** [comment]
@Mohron Absolutely! I appreciate it! 😄

**Comment by MarkHerhold** [comment]
@Mohron This took a bit longer than expected. You are now able to clear a subject's data via the dashboard on the new `subjects` page via the delete icon. We'll continue working on the UI and look into providing some sort options.

![image](https://cloud.githubusercontent.com/assets/4934732/23098969/879cffce-f629-11e6-9de8-92977458b42a.png)

Please try it out and let me know what you think!

**Comment by Mohron** [comment]
@MarkHerhold it looks like a beauty! Is this change live?

**Comment by MarkHerhold** [comment]
@Mohron It is! You may just need to reload/refresh the page.

**Comment by Mohron** [comment]
Can you add a link from the subject to the Metrics page filtered to that subject.

**Comment by MarkHerhold** [comment]
@Mohron Yes! That feature is actually in the works. I plan on having all those numbers in the table link to corresponding pages.

**Comment by Mohron** [comment]
Awesome!

**Comment by MarkHerhold** [comment]
Closing this now, but expect some UI improvements soon.

**Comment by Mohron** [comment]
Can I still get a way to clear all the data for an application/all subjects?

**Comment by MarkHerhold** [comment]
Can you tell me what are you trying to accomplish? Are you just trying to create start with a completely clean slate using the same application, or do you want to retain your achievements, criteria, and awards?

Currently, only historical events cannot be deleted without deleting the entire application, but this shouldn't cause you any problems.

**Comment by Mohron** [comment]
Just clearing the tracked events so I can start fresh with your new features and optimizations. I would prefer to keep achievements, criteria and awards.

**Comment by MarkHerhold** [comment]
This should do the trick! Let me know what you think.

![delete-multiple-subjects](https://cloud.githubusercontent.com/assets/4934732/25318332/316e8b14-285a-11e7-8d2a-2987e28745e7.gif)

**Comment by Mohron** [comment]
I'd recommend leaving the buttons there. Having them appear and shift down the records after selecting one is awkward imo.
