### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by Mohron** [BadgeUp/badgeup-browser-client#6]
The dashboard has some problems displaying on mobile. I'm even using a phablet! 
![screenshot_20170330-083025](https://cloud.githubusercontent.com/assets/3623122/24506507/60c9d9c6-1523-11e7-945e-51ebe3f906be.png)
![screenshot_20170330-083016](https://cloud.githubusercontent.com/assets/3623122/24506518/661c4ff8-1523-11e7-8b76-28383196a970.png)
![screenshot_20170330-083008](https://cloud.githubusercontent.com/assets/3623122/24506521/6a5df21a-1523-11e7-8834-d4b24d80692f.png)

.

**Comment by MarkHerhold** [comment]
Yeah, you've got a point there.

**Comment by Mohron** [comment]
I have to earn the top alpha tester title somehow don't I?

**Comment by MarkHerhold** [comment]
@Mohron HAHAHHA! Brilliant! I'll have to add an achievement for that!

**Comment by MarkHerhold** [comment]
The dashboard still isn't fully responsive on all pages (subjects and API keys need work), but it has gotten a lot better. As usual, try it out and let me know if you have comments/ideas.

![dashboard_responsive_homepage](https://cloud.githubusercontent.com/assets/4934732/25066103/be3ea630-21ea-11e7-8534-729b128660da.png)
